Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-11, with the labels that each got.

#519 chore(helm): improve memory + change cron for ci-export
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, skip

#522 chore: Enable log on Application Insight
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionScheduler.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionSchedulerTest.java
Labels: size/small, minor

#521 [PPANTT-182] feat: Support new Selfcare roles
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionType.java
Labels: enhancement, size/small, minor

#523 [PPANTT-205] fix: Added missing set of field activationDate
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
Labels: size/small, patch

#524 fix: Activation date
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
Labels: size/small, patch

#525 fix: Cron logs metadata
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionScheduler.java
Labels: size/small, patch
