Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-02, with the labels that each got.

#307 [VAS-709] fix: update delegation with role filter
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtil.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtilTest.java
  src/test/resources/response/externalapi/institution_response.json
Labels: bug, enhancement

#309 fix: Defined BundleCreateResponse for createBundle API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreateResponse.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
Labels: bug, size/small

#308 Added sops support
  .gitignore
  README.md
  infra/99_locals.tf
  infra/env/dev/encrypted_env
  infra/secrets.tf
  infra/sops.sh
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/LoggingAspect.java
  src/main/resources/logback-spring.xml
Labels: size/small

#310 fix: Fixed taxonomy service base url
  helm/values-dev.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: bug, size/small

#311 Hotfix: getDelegation
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/LoggingAspect.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
Labels: size/small

#312 Hotfix get delegation
  openapi/openapi.json
Labels: size/small

#313 [VAS-710] feat: Add opex dashboard GHA
  .github/workflows/create_dashboard.yml
  .opex/backoffice/env/prod/backend.ini
  .opex/backoffice/env/prod/backend.tfvars
  .opex/backoffice/env/prod/config.yaml
  .opex/backoffice/env/prod/terraform.tfvars
  .opex/backoffice/env/uat/backend.ini
  .opex/backoffice/env/uat/backend.tfvars
  .opex/backoffice/env/uat/config.yaml
  .opex/backoffice/env/uat/terraform.tfvars
Labels: enhancement, size/small

#315 [VAS-725] fix: bundle filter types
  infra/env/dev/encrypted.env
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
Labels: size/small

#316 Vas 710 fix create opex dashboard gha
  .github/workflows/create_dashboard.yml
  .opex/backoffice/env/prod/config.yaml
  .opex/backoffice/env/uat/config.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small

#314 [VAS-735] Change default timeout for Station type A primitive
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
Labels: size/small

#319 bug fixing: RoleType
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/test/resources/application.properties
Labels: size/small

#320 [VAS-752] feat: update psp code mapping
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtil.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtilTest.java
Labels: enhancement, size/small

#321 new terraform state
  .opex/backoffice/env/prod/backend.tfvars
  .opex/backoffice/env/uat/backend.tfvars
Labels: size/small

#318 [VAS-741] feat: Implemented afm-marketplace APIs to manage bundles
  .DS_Store
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/Bundle.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/large

#322 [VAS-693] feat: Changed getBrokerAndPspDetails API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
Labels: enhancement, size/small

#323 [VAS-694] feat: Update PUT PSP API to use psp tax code
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
Labels: size/small

#324 [VAS-695] Changed getFirstValidChannelCode API path param
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
Labels: enhancement, size/small

#325 [VAS-696] feat: Disassociate PSP from channel with fiscal code
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelPspResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelPsp.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
Labels: size/small
