Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-08, with the labels that each got.

#478 fix: Date format
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java
Labels: size/small, patch

#479 hotfix: Station/Channel not in wrapper
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: size/small, patch, hotfix

#480 [PPANTT-88] feat: Add pagopa operator's mail to bundle scheduler's notification
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
  src/test/resources/application.properties
Labels: size/small, minor

#481 chore: Merge main
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/PspData.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: size/small, skip

#465 Next
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/CreditorInstitutionMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/CreditorInstitutionStationEdit.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationEditResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/MaintenanceHoursSummaryResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceListResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceListState.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/OffsetDateTimeDeserializer.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
  src/test/resources/application.properties
Labels: size/large, minor

#482 [PPANTT-93] feat: Add api key ACA
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
Labels: size/small, minor

#484 fix: Change empty string to null in products subscription config
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
Labels: size/small, patch

#485 [PPANTT-99] feat: New filters PSP bundles' list
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: minor

#487 fix: Commission bundle mail notification
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java
  src/main/resources/templates/expiringBundleEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small, patch
