Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-07, with the labels that each got.

#447 [VAS-1070] feat: Change station and channel detail view on pending update
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/PspChannelPaymentTypes.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/WrapperStationList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/resources/templates/channelReviewRequestedEmail.html
  src/main/resources/templates/stationReviewRequestedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: enhancement, size/large, minor

#450 [VAS-962] feat: Implement authorizer when creating GPD key
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small, minor

#452 [VAS-1146] feat: Introduce new boolean "cart" for bundles
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/Bundle.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/Channel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
Labels: size/small, minor

#454 Next Release 2.17.0
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/Bundle.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/Channel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
Labels: size/small, minor

#458 [VAS-1168] feat: rework get institutions
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitutionProduct.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: minor

#460 hotfix getusers
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: bug, size/small, patch

#461 [VAS-1203] open ticket when a bundle is created
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreateResponse.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small, patch

#464 feat: rollback on getInstitutions service
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: size/small, minor

#453 [VAS-981] feat: Introduce new flags "standIn" & "aca" for CI-station relation
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationEditResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: enhancement, size/large, minor

#474 fix: Mapper for new flags standIn & aca
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/CreditorInstitutionMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/CreditorInstitutionStationEdit.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationEditResource.java
Labels: patch

#475 [PAGOPA-1992] regenerate key
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small, patch

#466 [PPANTT-47] feat: API create stations' maintenance
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/CreateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/OffsetDateTimeDeserializer.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: minor

#467 [PPANTT-37] feat: API update stations' maintenance
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/UpdateStationMaintenance.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: size/small, minor

#468 [PPANTT-38] feat: API get stations' maintenance list
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceListResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceListState.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: size/small

#476 Hotfix legal number
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/PspData.java
Labels: size/small, patch

#469 [PPANTT-35] feat: add station maintenance summary api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/MaintenanceHoursSummaryResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: size/small, minor

#472 [PPANTT-34] feat: API delete stations' maintenance
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: size/small, minor

#473 [PPANTT-48] feat: Add finish maintenance API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/MaintenanceHoursSummaryResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
Labels: enhancement, size/small, minor

#477 fix: Path api-config api station maintenance
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
Labels: bug, size/small, patch
