Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-03, with the labels that each got.

#326 Opex dashboard
  .github/workflows/create_dashboard.yml
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .opex/backoffice/env/uat/config.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#330 [VAS-779] feat: add taxonomy api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/TaxonomyEntity.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyServiceTest.java
Labels: enhancement, size/small

#331 [VAS-794] feat: update bundle apis taxonomy
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundlesResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/small

#333 [VAS-804] feat: Add accept public bundle subscription request API
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/small

#334 Feature flags
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/FeatureFilterConfigurations.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/OperationFeatureFilter.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/TargetingContextAccessorImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BaseController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/featureflags/FeatureFlags.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/bootstrap.properties
  src/main/resources/logback-spring.xml
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/SelfCarePagoPaBackofficeApplicationTest.java
  src/test/resources/application.properties
  src/test/resources/bootstrap.properties
Labels: size/large

#336 [VAS-838] fix: updated channel generation starting from psp tax code
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
Labels: bug, size/small

#337 [VAS-769] feat: Create api key bo external
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AzureApiManagerClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/feign/AuthorizerConfigFeignConfigImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/Authorization.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationEntity.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationGenericKeyValue.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationMetadata.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwnerType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/resources/application.properties
Labels: size/large

#341 fix: Azure secret
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  src/main/resources/bootstrap.properties
Labels: size/small

#340 [VAS-853] feat: Handle backoffice external new product
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small

#338 [VAS-791] feat: introducing getBundlesByEc API on CommissionBundleCon…
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small

#342 fix openapi
  openapi/openapi.json
Labels: size/small

#343 fix Azure Client Credential
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/AzureCredential.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/resources/application.properties
Labels: size/small

#344 [VAS-862] fix: Updated available-code service to use brokerCode
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
  src/test/resources/application.properties
  src/test/resources/bootstrap.properties
Labels: bug, size/small

#345 fix: Fixed filter by name for getCiBundles type global
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: bug, size/small

#346 [VAS-868] fix psp create/update
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/FeatureFilterConfigurations.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/OperationFeatureFilter.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/PaymentServiceProvider.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/PaymentServiceProviderDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtil.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtilTest.java
Labels: size/small

#347 [VAS-840] Improved external APIs error handling
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/IbanController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/ErrorHandler.java
Labels: size/small

#349 fix: Fixed createIban openapi response
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/IbanController.java
Labels: bug, size/small

#350 [VAS-689] feat: Add ci broker delegation page api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertDelegationExternalToMyCIResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationPage.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
Labels: size/large

#351 fix: apiconfig parameter
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
Labels: size/small

#352 Remove cache from getCIBrokerDelegation API
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java
Labels: size/small

#353 Add error handling on get cbill api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
Labels: size/small
