Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-09, with the labels that each got.

#486 [PPANTT-101] feat: Add export PSP bundle api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportServiceTest.java
Labels: enhancement, minor

#489 Update next with new release
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch

#490 Next release
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, minor

#491 [PPANTT-104] fix: Add delegations to authorizer for all GPD & ACA products
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small, patch

#492 [PPANTT-103] chore: Avoid jira ticket creation below uat env
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClient.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClientTest.java
Labels: size/small, patch

#495 hotfix: Checks on environment
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClient.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClientTest.java
Labels: size/small, patch, hotfix

#496 hotfix: [PPANTT-110] Handle legacy station and channel update
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityChannels.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: size/small, patch, hotfix

#498 hotfix: [PPANTT-113] Station and Channel code generation
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/Station.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/Stations.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperChannelsRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/StringUtils.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: patch, hotfix

#499 [PPANTT-72] feat: Add new fields to Station's models for REST endpoint and flag payment options
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/StationDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
Labels: size/small, minor

#501 updated openapi
  openapi/openapi.json
Labels: size/small, skip

#502 [PPANTT-141] fix: Re-add station's status mapping in station details API
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: size/small, patch
