Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-05, with the labels that each got.

#370 response validator
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GpdClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/TaxonomyClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/ResponseValidator.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/BrokerPspDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProviderDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProviderResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProvidersResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PspChannelsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Institution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionInfo.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PspBrokerControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: enhancement, size/large

#374 [VAS-1005] chore: Update PSP accept public bundle subscription
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PublicBundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small

#373 [VAS-957] Creditor Institution delete/create subscription request to public bundle
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundle.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleRequestId.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PublicBundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/resources/templates/createBundleSubscriptionRequestEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement

#376 [VAS-1007] Retrieve only active public bundles for CI
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small

#377 [VAS-1006] feat: Enable retrieve of payment contacts
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: size/small

#379 typo
  README.md
Labels: size/small, skip

#381 [VAS-1026] feat: Enable email notification in test environment
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
Labels: size/small, minor

#383 hotfix: required field
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
Labels: bug, size/small, patch

#384 Response validator
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
Labels: size/small, patch

#385 Test action
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, skip

#386 [VAS-1036] feat: Add get maintenance message api
  README.md
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/MaintenanceController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/MaintenanceEntity.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/maintenance/MaintenanceMessage.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/MaintenanceRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/MaintenanceService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/MaintenanceControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/MaintenanceServiceTest.java
Labels: enhancement, minor

#387 [VAS-1031] Remove required from get bundles response
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleTaxonomy.java
Labels: enhancement, size/small, minor

#388 timewindow
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/FeatureFilterConfigurations.java
Labels: size/small, patch

#389 fix: Add ecType to PSPBundleTaxonomy
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PSPBundleTaxonomy.java
Labels: size/small, patch

#390 [VAS-1009] feat: Add connection synchronous flag
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
Labels: enhancement, size/small, minor

#391 [VAS-1044] fix: Remove old bundle naming from email template
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/resources/templates/acceptPublicBundleSubscriptionEmail.html
  src/main/resources/templates/rejectPublicBundleSubscriptionEmail.html
Labels: size/small, patch

#392 new inputs for GHA Release and Deploy
  .github/workflows/release_deploy.yml
Labels: size/small, skip

#393 [VAS-948] feat: Update get stations API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/ConfigurationStatus.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStations.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationCodeResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: enhancement, size/large, minor

#394 [VAS-912] Updated get segregation codes api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/CreditorInstitutionMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/CreditorInstitutionMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/AvailableCodes.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/BrokerCreditorInstitutionDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAddress.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCode.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCodeList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutions.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/AllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: enhancement, size/small, minor

#398 fix: pre release
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCode.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCodeList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: bug, size/small, patch

#399 [fix-release-2] fix isNotBlank conditions
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
Labels: size/small, patch

#400 gitflow
  .github/workflows/cd_main.yml
  .github/workflows/cd_next.yml
  .github/workflows/check_pr.yml
  .github/workflows/ci_anchore.yml
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .github/workflows/github_scripts/check_source_branch.js
  .github/workflows/github_scripts/make_latest_release.js
  .github/workflows/github_scripts/update_code.js
  .github/workflows/release_deploy.yml
  .github/workflows/update_code.yml
  .github/workflows/update_gha.py
  .identity/00_data.tf
  .identity/03_github_environment.tf
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionDetails.java
Labels: size/large, skip

#396 [VAS-822] feat: Add operator station review
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/OperatorStationReview.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/resources/templates/acceptPublicBundleSubscriptionEmail.html
  src/main/resources/templates/channelCreationValidatedEmail.html
  src/main/resources/templates/channelUpdateValidatedEmail.html
  src/main/resources/templates/createBundleSubscriptionRequestEmail.html
  src/main/resources/templates/deleteBundleSubscriptionEmail.html
  src/main/resources/templates/rejectPublicBundleSubscriptionEmail.html
  src/main/resources/templates/stationCreationValidatedEmail.html
  src/main/resources/templates/stationReviewRequestedEmail.html
  src/main/resources/templates/stationUpdateValidatedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: enhancement, minor

#405 Hotfix flag async sync
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/Station.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
Labels: bug, size/small, patch

#403 [VAS-1047] feat: Add ApiResponse specifications to create & update bundle
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
Labels: size/small, skip

#401 [VAS-976] feat: add notice institutions api
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/InstitutionsClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/feign/InstitutionsFeignClientConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionsControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, size/small, minor

#406 [VAS-1063] feat: get notice institutions api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/InstitutionsClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertDelegationExternalToCreditorInstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionsControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsServiceTest.java
Labels: enhancement, size/large, minor

#408 update swagger at New APIM [Infra apply]
  infra/04_apim_api.tf
  infra/99_locals.tf
Labels: size/small, skip

#402 [VAS-1058] feat: Update CI - Station association API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: enhancement, size/small, minor

#409 [VAS-1071] PSP has to act as direct when use the bundles
  docker/run_docker.sh
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/small, patch

#411 pre_release
  .github/workflows/cd_main.yml
Labels: size/small, patch

#412 hotfix iban list
  .github/workflows/cd_next.yml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/IbanService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/IbanServiceTest.java
Labels: size/small, patch

#413 hotfix selfhosted runner
  .github/workflows/deploy_with_github_runner.yml
Labels: size/small, patch
