Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-06, with the labels that each got.

#410 fix: Openapi client generation
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionInfoResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/DelegationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionApiKeysResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/ProductResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionApiKeys.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: bug, size/large, patch

#416 hotfix: Bump maven-release version in github actions
  .github/workflows/cd_main.yml
  .github/workflows/cd_next.yml
  .github/workflows/release_deploy.yml
Labels: bug, size/small, patch

#417 hotfix
  .github/workflows/cd_main.yml
Labels: size/small, patch

#420 feat: Update ci data model
  .github/workflows/cd_main.yml
  .github/workflows/cd_next.yml
  .github/workflows/check_pr.yml
  .github/workflows/ci_anchore.yml
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/github_scripts/check_source_branch.js
  .github/workflows/github_scripts/make_latest_release.js
  .github/workflows/release_deploy.yml
  .github/workflows/update_code.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java
Labels: size/large, patch

#415 [VAS-806] feat: Add private bundle recipient table API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleSubscriptionStatus.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleSubscriptionsDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleSubscriptionsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleOffers.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspBundleOffer.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/small, minor

#427 fix: Station validation flow
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
Labels: bug, size/small, patch

#426 fix: updated notices ci client
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/InstitutionsClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
Labels: size/large, patch

#425 [VAS-959] feat: Add CI private bundle table API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleSubscriptionStatus.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCIOffers.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleOffer.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundles.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/large, minor

#429 fix: Deploy
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  openapi/openapi.json
  pom.xml
Labels: size/small

#430 [VAS-1085] feat: Add mail notification on bundle offer delete
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/resources/templates/deleteBundleSubscriptionOfferEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: enhancement, size/small, minor

#423 Deploy Pull Request Branch
  .github/workflows/ci_code_review.yml
  .github/workflows/deploy_with_github_runner.yml
  infra/04_apim_api.tf
  infra/04_apim_api_staging.tf.disabled
  infra/99_variables.tf
  infra/policy/_base_policy.xml
  src/main/resources/application.properties
Labels: skip

#432 Feign Timeout
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/resources/application.properties
Labels: bug, size/small, patch

#424 [VAS-759] new CSV ci export params
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/BrokerInstitutionEntity.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/AllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportService.java
Labels: enhancement, size/small, minor

#433 [VAS-990] feat: Add expiring bundles mail notification job
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/Bundle.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java
  src/main/resources/application.properties
  src/main/resources/templates/deleteBundleEmail.html
  src/main/resources/templates/expiringBundleEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, size/small, minor

#434 [VAS-1119] feat: Improvement on CI station association
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/CreditorInstitutionMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCode.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCodeList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/client/CreditorInstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/resources/response/service/get_creditor_institution_details_ok.json
  src/test/resources/response/service/get_creditor_institutions_ok.json
  src/test/resources/response/service/post_creditor_institution_ok.json
Labels: enhancement, size/small, minor

#436 Print notice path
  .github/workflows/cd_main.yml
  .github/workflows/ci_code_review.yml
  .github/workflows/ci_integration_test.yml
  .github/workflows/deploy_with_github_runner.yml
  infra/04_apim_api.tf
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: bug, size/large, patch

#437 fix: Delete bundle
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/SelfCarePagoPaBackofficeApplication.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/AllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: bug, size/small, patch

#441 hotfix pspcode when abi is N/A
  .github/workflows/ci_code_review.yml
  infra/04_apim_api.tf
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtil.java
Labels: size/small, patch

#438 feat: Review channels flow
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/OperatorChannelReview.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/Channels.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannels.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/resources/templates/channelReviewRequestedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: enhancement, size/large, minor

#439 [VAS-1122] feat: Remove unused API for Station and Channels entity
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: enhancement, size/small, minor

#444 [VAS-1103] feat: Add new field pspBusinessName to bundle details
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
Labels: size/small, minor

#445 Update next with wrapper hotfix
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityStation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityStations.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/WrapperStationList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperStationsRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: size/small, minor

#446 [VAS-1133] feat: Add new api key for printPaymentsNotice product
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionScheduler.java
Labels: size/small, minor

#449 [VAS-1151] hotfix: cast exception during export job
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperStationsRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/AllPages.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionSchedulerTest.java
Labels: size/small, patch
