Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-10, with the labels that each got.

#504 [PPANTT-138] feat: add standin flag
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/StationDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: size/small, minor

#505 Next 2.26.0
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/StationDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannel.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
Labels: size/small, minor

#507 [PPANTT-153] fix: Improved error handling on authoizer config update
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small, patch

#508 [PPANTT-153] fix: Error handling in dissociate CI station
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: size/small, patch

#509 [PPANTT-151] feat: Reworked taxonomy query
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
Labels: size/small, minor

#510 Ppantt 151 rework taxonomy query
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: minor

#511 Fix codes
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
Labels: size/small, patch, hotfix

#512 Fix codes
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
Labels: bug, size/small, patch

#514 fix: codes
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
Labels: size/small, patch

#513 Next release 2.27
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
Labels: size/small, minor

#515 [PPANTT-55] feat: Rework getInstitutions
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertUserInstitutionToInstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/InstitutionToInstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Institution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionBaseResources.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/UserProductRole.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitutionProduct.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: size/large, minor

#516 Next release 2.27
  .github/workflows/ci_code_review.yml
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertUserInstitutionToInstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/InstitutionToInstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Institution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionBaseResources.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/UserProductRole.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitutionProduct.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResourceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
Labels: size/large, minor

#517 fix: Conversion Institution to InstitutionBase for pagopaOperator
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionToInstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertUserInstitutionToInstitutionBase.java
Labels: size/small, patch

#518 [PPANTT-172] fix: PSP API key authorizer configuration
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/client/CIStationSegregationCodesList.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/UserProductRole.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/large, patch
