Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-04, with the labels that each got.

#354 [VAS-684] feat: Retrieve organization's payments receipts
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GpdClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/feign/GpdFeignConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/paymentsreceipts/ReceiptModelResponse.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/paymentsreceipts/ReceiptsInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentsReceiptsService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentsReceiptsServiceTest.java
  src/test/resources/application.properties
Labels: enhancement

#356 [VAS-691] feat: Add delegation details page API
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/TaxonomyEntity.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertCreditorInstitutionViewToCIBrokerStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CIPaymentContact.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionContactsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionView.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionsView.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerStationPage.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionProductUsers.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/tavoloop/TavoloOpResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TavoloOpRepository.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/OperativeTableService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/OperativeTableServiceTest.java
Labels: enhancement, size/large

#358 [VAS-773] feat: add forwarder test
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/sops.sh
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ForwarderTestClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/feign/ForwarderFeignConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationTestDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/TestResultEnum.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/TestStationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/resources/application.properties
Labels: enhancement, minor

#359 [VAS-838] feat: delete broker api config
  infra/env/dev/encrypted.env
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PspBrokerController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/BrokerPspDetailsDto.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/BrokerPspResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/BrokersPspResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/BrokerPsp.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/BrokersPsp.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PspBrokerService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PspBrokerControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PspBrokerServiceTest.java
Labels: enhancement, size/large

#357 fix: Fixed getPaymentReceiptDetail openapi specs
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsController.java
Labels: size/small

#360 [VAS-929] fix: Add new field to delegation list api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertDelegationExternalToCIBrokerDelegationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
Labels: size/small

#361 [VAS-914] feat: Implemented debtorOrIuv getPaymentsReceipts filter
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ForwarderTestClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GpdClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/paymentsreceipts/PaymentsResult.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/paymentsreceipts/ReceiptsInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentsReceiptsService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentsReceiptsControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentsReceiptsServiceTest.java
Labels: enhancement, size/small

#362 [VAS-952] Improve for PROD release
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/repository/TransactionalBulkDAOTest.java
  src/test/java/utils/MemoryAppender.java
Labels: size/small

#364 [VAS-799] feat: Add Retrieve public bundle's subscriptions APIs
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleFee.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CISubscriptionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleCISubscriptionsDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleCISubscriptionsResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleSubscriptionStatus.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleAttribute.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspBundleRequest.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspCiBundleAttribute.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspRequests.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/TransferCategoryRelation.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/PageInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/CreditorInstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/large

#368 [VAS-945] feat: Add delete bundle subscription api
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/ThymeleafTemplateConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CISubscriptionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleCISubscriptionsDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreditorInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleDetails.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/email/EmailMessageDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/SelfcareProductUser.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/Institution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
  src/main/resources/templates/channelCreationValidatedEmail.html
  src/main/resources/templates/channelUpdateValidatedEmail.html
  src/main/resources/templates/deleteBundleSubscriptionEmail.html
  src/main/resources/templates/logo-pagopa.png
  src/main/resources/templates/stationCreationValidatedEmail.html
  src/main/resources/templates/stationUpdateValidatedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
Labels: size/large

#369 Selfcare Role Log
  CODEOWNERS
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwnerType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: bug, size/small
