Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2024-12, with the labels that each got.

#527 [PPANTT-215] feat: Send emails to CIs in UAT & PROD
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/resources/application.properties
Labels: size/small, minor

#528 [PPANTT-218] fix: Deploy gha
  .github/workflows/deploy_with_github_runner.yml
Labels: size/small, skip

#529 fix: helm
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#530 [PPANTT-215] feat: Add environment info in mail content
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java
  src/main/resources/templates/acceptBundleSubscriptionOfferEmail.html
  src/main/resources/templates/acceptBundleSubscriptionRequestEmail.html
  src/main/resources/templates/channelReviewRequestedEmail.html
  src/main/resources/templates/createBundleSubscriptionOfferEmail.html
  src/main/resources/templates/createBundleSubscriptionRequestEmail.html
  src/main/resources/templates/deleteBundleEmail.html
  src/main/resources/templates/expiringBundleEmail.html
  src/main/resources/templates/stationReviewRequestedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
Labels: size/small, minor

#531 [PPANTT-222] fix: BO external authorizer config
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: size/small, patch

#533 [PPANTT-223] feat: Add FdR QI KPI sub key
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionScheduler.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/templates/acceptBundleSubscriptionOfferEmail.html
  src/main/resources/templates/acceptBundleSubscriptionRequestEmail.html
  src/main/resources/templates/channelReviewRequestedEmail.html
  src/main/resources/templates/createBundleSubscriptionOfferEmail.html
  src/main/resources/templates/createBundleSubscriptionRequestEmail.html
  src/main/resources/templates/deleteBundleEmail.html
  src/main/resources/templates/expiringBundleEmail.html
  src/main/resources/templates/stationReviewRequestedEmail.html
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/resources/application.properties
Labels: size/large, minor

#534 Next release 2.35.0
  .identity/00_data.tf
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: minor
