Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2025-04, with the labels that each got.

#551 [PIDM-441] chore: VA-PT Step 2
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/JwtAspect.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/security/JwtSecurity.java
Labels: size/small, minor

#552 chore: [PIDM-441] VA-PT Step 3
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/JwtAspect.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/ChannelController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/security/JwtSecurity.java
Labels: size/small, patch

#553 chore: [PIDM-441] VA-PT Step 4
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
Labels: size/small, patch

#556 feat: update helm chart version
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .terraform-version
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: patch
