Repository pagopa/pagopa-selfcare-ms-backoffice-backend, pull requests merged in 2025-02, with the labels that each got.

#535 chore(pom): new versions
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small

#536 fix: PIDM-153 Resolve Update Station StackOverflow bug
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
Labels: size/small, patch

#532 [PPANTT-183] feat: AWS Quicksight Dashboard API
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/env/dev/encrypted.env
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/AwsQuicksightConfig.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionToInstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertUserInstitutionToInstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/InstitutionToInstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionBase.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetailResource.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/BusinessData.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/Institution.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionInfo.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/Onboarding.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/SupportContact.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/quicksightdashboard/QuicksightEmbedUrlResponse.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitutionProduct.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserProductStatus.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/AWSSessionTagCustomSerializer.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
  src/main/resources/application.properties
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponentTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResourceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
  src/test/resources/application.properties
Labels: size/large, minor

#538 [PIDM-206] fix: paged get users
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
Labels: bug, size/small, patch

#537 feat: [PIDM-87] Improvements quicksight dashboard
  openapi/openapi.json
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightController.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/SelfCareUser.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/Onboarding.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/security/PagopaAuthenticationStrategy.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightControllerTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
Labels: size/small, patch

#539 feat: Added pspName parameter to quicksight dashboard url
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClient.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClientTest.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
Labels: size/small, patch

#540 [PIDM-45] chore(exception): propagate printit downstream dependency's 400
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java
  src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
  src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsServiceTest.java
Labels: size/small, patch
